{
 "title": "eCommerce assistant",
 "description": "On this dashboard you can see the metrics for the eCommerce assistant project.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Dialogs",
   "type": "table",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select tstz, \r\n      question, \r\n      answer, \r\n      response_time, \r\n      relevance \r\n  from dialogs \r\n  ORDER BY tstz desc\r\n  limit 10"
    }
   ]
  },
  {
   "title": "Feedback",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(case when feedback > 0 then 1 else 0 end) as thumbs_up,\r\n        sum(case when feedback < 0 then 1 else 0 end) as thumbs_down\r\n    from feedback "
    }
   ]
  },
  {
   "title": "Total tokens",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(total_tokens) as total_tokens,\r\n        sum(eval_total_tokens) as eval_total_tokens\r\n    from dialogs"
    }
   ]
  },
  {
   "title": "Total cost",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(total_cost) + sum(eval_total_cost) as total_cost\r\n  from dialogs"
    }
   ]
  },
  {
   "title": "Relevance spread",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(case when relevance = 'Relevant' then 1 else 0 end) as relevant,\r\n        sum(case when relevance = 'Not relevant' then 1 else 0 end) as non_relevant,\r\n        sum(case when relevance = 'Partly relevant' then 1 else 0 end) as partly_relevant\r\n    from dialogs "
    }
   ]
  }
 ]
}